
version: '3.8'

services:
  veeam-status:
    image: node:20-alpine
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/YOUR_REPO_URL.git /app &&
        cd /app &&
        npm install &&
        npm run build &&
        npm install -g serve &&
        serve -s dist -l 8080
      "
    environment:
      - NODE_ENV=production
    networks:
      - veeam-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  veeam-net:
    driver: overlay

