
version: '3.8'

services:
  veeam-status:
    image: node:20-alpine
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone --depth 1 https://github.com/scottifydev/veeam-status-stream.git /app &&
        cd /app &&
        npm install &&
        npm install vite@latest @vitejs/plugin-react-swc@latest &&
        npx vite build &&
        npm install -g serve &&
        serve -s dist -l 8080
      "
    environment:
      - NODE_ENV=production
      - DOMAIN_NAME=${DOMAIN_NAME:-veeam-status.example.com}
    networks:
      - veeam-net
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.veeam-status.rule=Host(`${DOMAIN_NAME:-veeam-status.example.com}`)"
        - "traefik.http.services.veeam-status.loadbalancer.server.port=8080"
        - "traefik.http.routers.veeam-status.entrypoints=websecure"
        - "traefik.http.routers.veeam-status.tls=true"

networks:
  veeam-net:
    driver: overlay
  traefik-public:
    external: true
